from typing_extensions import override

from .encoder_nodes import *
from .embedding_nodes import *
from .image_nodes import *
from .preset_nodes import *
from .vlm_nodes import *
from .minimax_h3_vlm_nodes import *
from .parameter_nodes import *
from .utils_nodes import *
from .legacy_nodes import *
from .scheduler_nodes import *
from .loader_nodes import *
from .text_nodes import *
from .textgen_nodes import *
from .composite_nodes import *
from .logic_math_nodes import *
from .patcher_nodes import *
from .lama_nodes import *
from .model_nodes import *

from comfy_api.latest import ComfyExtension, io
from .node_replacements import register_replacements
from .node_metadata import enrich_node_list
from .scheduler_helpers import register_scheduler_handlers

class SamplingUtils(ComfyExtension):
    @override
    async def get_node_list(self) -> list[type[io.ComfyNode]]:
        return enrich_node_list([
            UC_AdjustedResolutionParameters,
            UC_ResolutionSelectorExtended,
            UC_VideoResolutionSelector,
            UC_ImageScaleAndResolutionPicker,
            UC_Image_Color_Noise,
            UC_ExtractPrevalentColors,
            UC_TextEncodeFlux2SystemPrompt,
            UC_TextEncodeKleinSystemPrompt,
            UC_TextEncodeKrea2SystemPrompt,
            UC_TextEncodeLtxv2SystemPrompt,
            UC_TextEncodeZITSystemPrompt,
            UC_TextEncodeZImageThinkPrompt,
            UC_TextEncodeSystemPrompt,
            UC_WeightedTextEncodeSystemPrompt,
            UC_TextEncodeSystemEditAdvanced,
            UC_TextEncodeGemmaSystemEditAdvanced,
            UC_AdvancedVisualConditioningEncode,
            UC_AdvancedVisualConditioningEncodeTokenFusion,
            UC_MiniMaxH3MediaConfig,
            UC_MiniMaxH3VLMGuide,
            UC_MiniMaxH3RefExtract,
            UC_MiniMaxH3AudioRefExtract,
            UC_MiniMaxH3RefLoad,
            UC_MiniMaxH3RefSave,
            UC_MiniMaxH3RefApply,
            UC_AdvancedMiniMaxH3ImageToVideo,
            UC_AdvMiniMaxH3ImageToVideoTokenFusion,
            UC_AdvMiniMaxH3ImageToVideoTemporalFusion,
            UC_AdvMiniMaxH3ImageToVideoTemporalTokenFusion,
            UC_AdvancedVisConEncoder,
            UC_AdvancedVisConEncoderTokenFusion,
            UC_VisualConsensusConfiguration,
            UC_AdvancedConsensusConfiguration,
            UC_VLMInputEmbeds,
            UC_Krea2TokenAttentionWeight,
            UC_Krea2TokenAttentionWeightTokenFusion,
            UC_ScaledBiasTextEncodeFlux2SystemPrompt,
            UC_ScaledBiasTextEncodeKleinSystemPrompt,
            UC_ScaledBiasTextEncodeLtxv2SystemPrompt,
            UC_ScaledBiasTextEncodeZITSystemPrompt,
            UC_ScaledBiasTextEncodeZImageThinkPrompt,
            UC_ScaledBiasTextEncodeSystemPrompt,
            UC_ModifyMask,
            UC_MaskToBoundingBox,
            UC_ImageBlendByMask,
            UC_ImagePad,
            UC_NoHaloLoHaloDownscale,
            UC_CropByMask,
            UC_StagedLayerCrops,
            UC_ImageCropMerge,
            UC_ImageAndMaskResize,
            UC_ResizeMask,
            UC_BackgroundRemovalPreserveAlpha,
            UC_FaceRemovalPreserveAlpha,
            UC_UnifiedBackgroundReplace,
            UC_StagedLayeredBackgroundComposite,
            UC_StagedIndividualComposites,
            UC_StagedLayeredBackgroundCompositeOptions,
            UC_StagedMediaPipeFaceOptions,
            UC_StagedMediaPipeFaceBackgroundComposite,
            UC_LayeredBackgroundComposite,
            UC_MediaPipeFaceCompositeOptions,
            UC_MediaPipeFaceComposite,
            UC_SystemMessagePresets,
            UC_SystemMessageVideoPresets,
            UC_InstructPromptPresets,
            UC_InstructPromptVideoPresets,
            UC_BonusPromptPresets,
            UC_BonusPromptVideoPresets,
            UC_EditTargetPresets,
            UC_EditOpPresets,
            UC_CameraShotPresets,
            UC_VLMSysInstrPresets,
            UC_VLMSysInstrPresetsExperimental,
            UC_VLMSysInstrLegacyPresets,
            UC_VLMSysQueryAddPresets,
            UC_VLMSysQueryRawPresets,
            UC_VLMSysInstrAdvPresets,
            UC_VLMSysInstrAdvPresetsExperimental,
            UC_MiniMaxH3VLMSysInstrPresets,
            UC_MiniMaxH3VLMSysInstrPresetsExperimental,
            UC_MiniMaxH3VLMSysInstrAdvPresets,
            UC_MiniMaxH3VLMSysInstrAdvPresetsExperimental,
            UC_LegacyPromptPresets,
            UC_UnifiedPresets,
            UC_AttentionBiasTextEncode,
            UC_EmbeddingDetokenizerAnalysis,
            UC_TagNormalizeCombine,
            UC_ImageToVideoPrompt,
            UC_LoadImagePath,
            UC_LoadImageDirectory,
            UC_SampleVideoFramesAsImages,
            UC_MiniMaxH3RefVid,
            UC_ImagesToVideoTimeline,
            UC_VideoTimelineText,
            UC_HighResolutionTileSplit,
            UC_HighResolutionTileAccumulator,
            UC_ListToImageBatch,
            UC_FromList,
            UC_SwitchInverseNode,
            UC_SoftSwitchInverseNode,
            UC_IntegerRangeRandom,
            UC_SeedCluster,
            UC_FromSeedCluster,
            UC_GetJsonValue,
            UC_ImageMatchPropertiesNode,
            UC_OpticalFlowComposite,
            UC_ImageInwardEdgeFill,
            UC_ImageIterativeStretchFill,
            UC_TextOverlayNode,
            UC_RandInt,
            UC_StaticInt,
            UC_StaticFloat,
            UC_RandIntRange,
            UC_TextConsensusBlendConfig,
            UC_VisualFusionConfig,
            # UC_MiniMaxH3RadialAttentionConfig,
            UC_MiniMaxH3SlaAttentionConfig,
            UC_UnifiedAttentionPatcher,
            UC_Ideogram4DebannerPatch,
            UC_MiniMaxH3ClipProjectionPatcher,
            UC_MiniMaxH3PDDAcc,
            UC_MiniMaxH3Cache,
            UC_MiniMaxH3Spectrum,
            UC_ConditioningConsensusBlend,
            UC_TextGenerate,
            UC_TextGenerateQwen35SystemPrompt,
            UC_ColorConvertNode,
            UC_ExtractBoundingBox,
            UC_ExtractMask,
            UC_ExtractImage,
            UC_Ideogram4BoundingBoxCrop,
            UC_AdjustBoundingBox,
            UC_Krea2LayerProbe,
            UC_Krea2LayerAblator,
            UC_Krea2InputEmbeds,
            UC_Qwen3VLInputEmbeds,
            UC_EncoderNodesGuide,
            UC_CompositeNodesGuide,
            UC_HighResolutionTilingGuide,
            UC_MarkdownPreview,
            UC_LoraLoaderCLIPOnly,
            UC_SAM31CheckpointLoader,
            UC_SAM3Detect,
            UC_LoadImageWithAlpha,
            UC_LoadLaMaModel,
            UC_LaMaInpaint,
            UC_BoldFrakturTextStyle,
            UC_UnBoldFrakturTextStyle,
            UC_WordJoiner,
            UC_UnWordJoiner,
            UC_JSONMinifyRepair,
            UC_StringUnescape,
            UC_TextConcatenateAutogrow,
            UC_TextConcatenateListsAutogrow,
            UC_Newline,
            AdjustedResolutionParameters,
            ResolutionSelectorExtended,
            ImageScaleAndResolutionPicker,
            Image_Color_Noise,
            TextEncodeFlux2SystemPrompt,
            TextEncodeKleinSystemPrompt,
            TextEncodeLtxv2SystemPrompt,
            TextEncodeZITSystemPrompt,
            TextEncodeZImageThinkPrompt,
            TextEncodeSystemPrompt,
            ScaledBiasTextEncodeFlux2SystemPrompt,
            ScaledBiasTextEncodeKleinSystemPrompt,
            TextEncodeSystemEditPlus,
            TextEncodeSystemEditPlusAdvanced,
            TextEncodeKrea2SystemEditPlusAdvanced,
            TextEncodeEditPlusAdvanced,
            TextEncodeKrea2SystemEditScaledAdv,
            TextEncodeKrea2SysEditScaledAdvAttn,
            TextEncodeGemmaSystemEditPlusAdvanced,
            ScaledBiasTextEncodeLtxv2SystemPrompt,
            ScaledBiasTextEncodeZITSystemPrompt,
            ScaledBiasTextEncodeZImageThinkPrompt,
            ScaledBiasTextEncodeSystemPrompt,
            ModifyMask,
            ImageBlendByMask,
            SystemMessagePresets,
            SystemMessageVideoPresets,
            InstructPromptPresets,
            InstructPromptVideoPresets,
            BonusPromptPresets,
            BonusPromptVideoPresets,
            EditTargetPresets,
            EditOpPresets,
            CameraShotPresets,
            VLMSysInstrPresets,
            VLMSysQueryAddPresets,
            VLMSysInstrAdvPresets,
            UnifiedPresets,
            AttentionBiasTextEncode,
            TagNormalizeCombine,
            SU_LoadImagePath,
            SU_LoadImageDirectory,
            SwitchInverseNode,
            SoftSwitchInverseNode,
            IntegerRangeRandom,
            ImageMatchPropertiesNode,
            OpticalFlowComposite,
            ImageInwardEdgeFill,
            ImageIterativeStretchFill,
            TextOverlayNode,
            RandInt,
            StaticInt,
            RandIntRange,
            LamaRemover,
            LamaRemoverIMG,
            TextGenerateQwen35SystemPrompt,
            ColorConvertNode,
            *LOGIC_MATH_NODES,
            *SCHEDULER_NODES,
        ])

    @override
    async def on_load(self) -> None:
        """Called by ComfyUI backend on startup to initialize resources and register API extensions."""
        register_scheduler_handlers()
        await register_replacements()

async def comfy_entrypoint() -> SamplingUtils:
    return SamplingUtils()
